### ISSUE TITLE
PyPi package

### ISSUE THREAD

**Issue by cpitclaudel** [cpitclaudel/alectryon#41]
Distributing Alectryon as a PyPi package would make it easier to install.  The steps are described here: https://packaging.python.org/tutorials/packaging-projects/

**Comment by Bruno-366** [comment]
there is a github workflow called `python-publish` for this.

```yml
# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*

```
